apiVersion: apps/v1
kind: Deployment
metadata:
  name: default
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default
    spec:
      containers:
      - name: default
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: default  
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: default
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: default-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: default
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50