apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet
  namespace: dev 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: dotnet
        image: week3myacr.azurecr.io/dotnet:latest
        ports:
        - containerPort: 8080
        envFrom: 
          - configMapRef:
              name: dotnet-config-map
      imagePullSecrets:
      - name: acr-secret
      
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet  
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: dotnet
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dotnet-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dotnet
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50  