apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1
  namespace: dev 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
      - name: web1
        image: week3myacr.azurecr.io/web1:latest
        volumeMounts:
        - mountPath: "/mnt/azure"
          name: azurefile
        ports:
        - containerPort: 80
      volumes:
      - name: azurefile
        persistentVolumeClaim:
          claimName: azurefile-pv
      imagePullSecrets:
      - name: acr-secret
      
---
apiVersion: v1
kind: Service
metadata:
  name: web1  
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: web1
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web1-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web1
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50  