apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-pv
  namespace: dev
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: azure-storage-acc-secret
    shareName: aksshare
    readOnly: false