apiVersion: v1
kind: PersistentVolume
metadata:
  name: azurefile-pv
  namespace: dev
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  azureFile:
    secretName: azure-secret
    shareName: nhodzic-jap-file-share
    readOnly: false